---
- name: install mysql
  yum: name=mysql state=present

- name: install mysql-server
  yum: name=mysql-server state=present

- name: install MySQL-python
  yum: name=MySQL-python state=present

- shell:  /usr/bin/mysql_install_db --user=mysql

- service: name=mysqld state=started enabled=yes

- shell: yum install -y http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm

- name: install zabbix
  yum: name=zabbix state=present

- name: install zabbix-server
  yum: name=zabbix-server state=present

- name: install zabbix-server-mysql
  yum: name=zabbix-server-mysql state=present

- name: install zabbix-web-mysql
  yum: name=zabbix-web-mysql state=present

- name: install zabbix-agent
  yum: name=zabbix-agent state=present

- mysql_db: name=zabbix encoding=utf8 collation=utf8_bin state=present 

- mysql_user: name=zabbix password=zabbix priv=zabbix.*:ALL state=present  

- shell: mysql -uroot zabbix < {{ item }}
  with_items:
     - schema.sql
     - images.sql
     - data.sql
  args:
    chdir: /usr/share/doc/zabbix-server-mysql-2.2.12/create/

- name: zabbix_server config
  copy: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf

- service: name=zabbix-server state=started enabled=yes

- service: name=zabbix-agent state=started enabled=yes

- name: zabbix gui
  copy: src=zabbix.conf dest=/etc/httpd/conf.d/zabbix.conf

- service: name=httpd state=started enabled=yes

- name: iptables
  copy: src=iptables dest=/etc/sysconfig/iptables

- service: name=iptables state=restarted enabled=yes
