# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
#  config.vm.provision "shell", path: "provision.sh"
#  config.vm.provision "shell", path: "ansible0/provision.sh"
  config.vm.box = "sbeliakou/centos-6.7-x86_64"
#  config.vm.network "forwarded_port", guest: 8080, host: 80
  config.vm.network :private_network, ip: "192.168.6.88"
  config.vm.provider :virtualbox do |v|
          v.name = "vmprov Zabbix"
  end 
  config.vm.hostname = "zabbixprov"
  
#  config.vm.provider "virtualbox" do |vb|
#    vb = config.vm.hostname
#  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = 'provision.yml'
    ansible.verbose = 'vv'
  end
end
